version: '3'

services:
  pgsql:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
        - 5432:5432
    volumes:
        - db-store:/var/lib/postgresql/data
        - ./infra/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
volumes:
  db-store: