version: '3'

services:
  # db:
  #   image: mysql:8
  #   container_name: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: secret
  #     MYSQL_DATABASE: react-bbs
  #     MYSQL_USER: react
  #     MYSQL_PASSWORD: react
  #     TZ: Asia/Tokyo
  #   ports:
  #       - 3306:3306
  #   volumes:
  #       - db-store:/var/lib/mysql
  #       - ./docker/conf/my.cnf:/etc/mysql/conf.d/my.cnf
  #   command: --default-authentication-plugin=mysql_native_password
  pgsql:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
        - 5432:5432
    volumes:
        - db-store:/var/lib/postgresql/data
        - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
volumes:
  db-store: