version: '3'

services:
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: react-bbs
      MYSQL_USER: react
      MYSQL_PASSWORD: react
      TZ: Asia/Tokyo
    ports:
        - 3306:3306
    volumes:
        - db-store:/var/lib/mysql
        - .docker/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    command: --default-authentication-plugin=mysql_native_password
volumes:
  db-store: